In [53]:
import pandas as pd

In [54]:
df=pd.read_csv('npcitxns.csv')

In [55]:
df.shape

(500000, 25)

In [56]:
df.head()

,NPCI_TXN_TYPE,NPCI_STATUS,TXNID,RRN,NPCI_CODE,DATE,TIME,AMOUNT,A,B,...,F,PAYEE_VPA,MCC,G,H,I,J,K,L,M
0,TX,U2,acd4bf6bc8b9045feb9eaf1a,638386246099,Z9,40424,210230,430.32,cb9274e72eb6406fba57211045db5fa5@axl,1,...,COB,Freeda_Oberbrunner13@gmail,2394,SBI,AIRP0000001,1,111,AXB,UTIB0003966,1
1,TX,U2,f67f7e3bac12df3c72ae8b67,462581399622,Z9,40424,210230,961.38,cb9274e72eb6406fba57211045db5fa5@axl,1,...,COB,Anna.Pfannerstill@gmail,1141,SBI,AIRP0000001,1,111,AXB,UTIB0003966,1
2,TX,U2,d5d38cda31dd427a454ecff4,681411347661,RB,40424,210230,562.65,cb9274e72eb6406fba57211045db5fa5@axl,1,...,COB,Uriah.Johnston56@hotmail,5367,SBI,AIRP0000001,1,111,AXB,UTIB0003966,1
3,TX,U2,25e491ccd1c3f6ecdb2a7bcc,165965113537,Z9,40424,210230,602.66,cb9274e72eb6406fba57211045db5fa5@axl,1,...,COB,Korbin_Casper72@hotmail,6798,SBI,AIRP0000001,1,111,AXB,UTIB0003966,1
4,TX,U2,dfffb4c7ec1f9d6ae715c2fb,868419032664,Z9,40424,210230,67.46,cb9274e72eb6406fba57211045db5fa5@axl,1,...,COB,Zander65@gmail,2033,SBI,AIRP0000001,1,111,AXB,UTIB0003966,1